### ISSUE TITLE
Stuck at 'Starting...' on windows

### ISSUE THREAD

**Issue by shao-shuai** [bclavie/RAGatouille#29] opened 2024-01-08 23:54 UTC
Trying to run the sample code, but stuck at the following line every time.

```python
[Jan 08, 15:49:04] #> Creating directory .ragatouille/colbert\indexes/my_index1 

#> Starting...
``` 

sample code

```python
from ragatouille import RAGPretrainedModel
from ragatouille.utils import get_wikipedia_page

RAG = RAGPretrainedModel.from_pretrained("colbert-ir/colbertv2.0")
my_documents = [get_wikipedia_page("Hayao_Miyazaki"), get_wikipedia_page("Studio_Ghibli")]
index_path = RAG.index(index_name="my_index", collection=my_documents)
```

I am using python 3.11.5 with conda.

**Comment by bclavie** [comment] 2024-01-09 00:07
Hey, please try wrapping your code in 
```python
if __name__ == "__main__":
```
aș per the README. This should do the trick, the issue is due to `multiprocessing` hanging.

**Comment by bclavie** [comment] 2024-01-09 00:11
Also please note -- I was just updating the README to give a better example where the collection is actually split into chunks! Do use this full code instead for a better demo:

```python
from ragatouille import RAGPretrainedModel
from ragatouille.utils import get_wikipedia_page
from ragatouille.data import CorpusProcessor

if __name__ == "__main__":
    RAG = RAGPretrainedModel.from_pretrained("colbert-ir/colbertv2.0")
    my_documents = [get_wikipedia_page("Hayao_Miyazaki"), get_wikipedia_page("Studio_Ghibli")]
    processor = CorpusProcessor()
    my_documents = processor.process_corpus(my_documents)
    index_path = RAG.index(index_name="my_index", collection=my_documents)
```

**Comment by shao-shuai** [comment] 2024-01-09 00:28
> Also please note -- I was just updating the README to give a better example where the collection is actually split into chunks! Do use this full code instead for a better demo:
> 
> ```python
> from ragatouille import RAGPretrainedModel
> from ragatouille.utils import get_wikipedia_page
> from ragatouille.data import CorpusProcessor
> 
> if __name__ == "__main__":
>     RAG = RAGPretrainedModel.from_pretrained("colbert-ir/colbertv2.0")
>     my_documents = [get_wikipedia_page("Hayao_Miyazaki"), get_wikipedia_page("Studio_Ghibli")]
>     processor = CorpusProcessor()
>     my_documents = processor.process_corpus(my_documents)
>     index_path = RAG.index(index_name="my_index", collection=my_documents)
> ```

thanks! Tried the new demo code (wrapped with 'if __name__ == "__main__":' also) and still not working. Got stuck at the same place. I am running it in jupyte lab.

**Comment by nigh8w0lf** [comment] 2024-01-09 04:52
I would recommend setting up and using your notebook through WSL.

**Comment by shao-shuai** [comment] 2024-01-09 05:55
> I would recommend setting up and using your notebook through WSL.

thanks, will give a try.

**Comment by bclavie** [comment] 2024-01-09 13:06
Oh my bad, I assumed this was ran in a script!

Yes, Windows support isn't something we're currently targeting. It appears to run well in notebooks on Windows 11 + WSL as per  https://github.com/bclavie/RAGatouille/issues/14. Closing this issue to centralise windows-related hangups there!

**Closed by bclavie** 2024-01-09 13:06 UTC
